/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : IDL.Text,
  'beds' : IDL.Nat,
  'sqft' : IDL.Nat,
  'address' : IDL.Text,
  'baths' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : IDL.Text,
    'beds' : IDL.Nat,
    'sqft' : IDL.Nat,
    'address' : IDL.Text,
    'baths' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };